name: Check formatting

on:
  workflow_dispatch:
  push:

jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install llvm protobuf-compiler
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: cargo fmt --all
        uses: clechasseur/rs-cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy lint and check
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install llvm protobuf-compiler glibc-source libgtk-3-dev libsoup2.4 webkit2gtk-4.0 javascriptcoregtk-4.0 node npm

      - uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - run: npm i -g yarn

      - name: Install yarn dependencies
        run: yarn --cwd ./Ecdar-GUI-Web install

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: clippy --all-targets --all-features
        uses: clechasseur/rs-clippy-check@v3
        with:
          args: --all-targets --all-features -- -D warnings

