name: Check formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  fmt:
    name: cargo fmt check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy lint and check
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install llvm protobuf-compiler glibc-source libgtk-3-dev libsoup2.4 webkit2gtk-4.0 javascriptcoregtk-4.0

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: 'Ecdar-GUI-Web/yarn.lock'

      - name: Install yarn dependencies
        run: cd Ecdar-GUI-Web && yarn install

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: clippy --all-targets --all-features
        uses: actions-rs/clippy-check@v1
        with:
          token : ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets -- -D warnings

